//
//  StyleKit.swift
//  Passing-Data
//
//  Created by Audrey Li on 4/10/15.
//  Copyright (c) 2015 shomigo.com. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfSegueIcon: UIImage?
        static var segueIconTargets: [AnyObject]?
        static var imageOfDelegateIcon: UIImage?
        static var delegateIconTargets: [AnyObject]?
        static var imageOfBlockIcon: UIImage?
        static var blockIconTargets: [AnyObject]?
        static var imageOfKvoIcon: UIImage?
        static var kvoIconTargets: [AnyObject]?
        static var imageOfNotificationIcon: UIImage?
        static var notificationIconTargets: [AnyObject]?
        static var imageOfCredit: UIImage?
        static var creditTargets: [AnyObject]?
    }

    //// Drawing Methods

    public class func drawSegue(#frame: CGRect, iconColor: UIColor) {


        //// Subframes
        let frame2 = CGRectMake(frame.minX + 43, frame.minY + 47, frame.width - 85, frame.height - 98)


        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 20, frame.minY + 20, frame.width - 39.5, frame.height - 39.5))
        iconColor.setStroke()
        oval2Path.lineWidth = 5
        oval2Path.stroke()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(frame2.minX + 0.06466 * frame2.width, frame2.minY + 0.52001 * frame2.height))
        bezier3Path.addLineToPoint(CGPointMake(frame2.minX + 0.91810 * frame2.width, frame2.minY + 0.52001 * frame2.height))
        bezier3Path.moveToPoint(CGPointMake(frame2.minX + 0.49569 * frame2.width, frame2.minY + 0.02427 * frame2.height))
        bezier3Path.addLineToPoint(CGPointMake(frame2.minX + 0.91810 * frame2.width, frame2.minY + 0.51942 * frame2.height))
        bezier3Path.addLineToPoint(CGPointMake(frame2.minX + 0.49569 * frame2.width, frame2.minY + 0.99515 * frame2.height))
        iconColor.setStroke()
        bezier3Path.lineWidth = 10
        bezier3Path.stroke()
    }

    public class func drawDelegat(#frame: CGRect, iconColor: UIColor) {


        //// Subframes
        let frame2 = CGRectMake(frame.minX + 48, frame.minY + 57, frame.width - 91, frame.height - 110)
        let group2: CGRect = CGRectMake(frame2.minX + 5.5, frame2.minY + 6.5, frame2.width - 17, frame2.height - 15)


        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 20, frame.minY + 20, frame.width - 39.5, frame.height - 39.5))
        iconColor.setStroke()
        oval2Path.lineWidth = 5
        oval2Path.stroke()


        //// Group 2
        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(group2.minX + 0.36559 * group2.width, group2.minY + 0.22368 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.18280 * group2.width, group2.minY + 0.00000 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.36559 * group2.width, group2.minY + 0.10015 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.28375 * group2.width, group2.minY + 0.00000 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.22368 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.08184 * group2.width, group2.minY + 0.00000 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.10015 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.18280 * group2.width, group2.minY + 0.44737 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.34722 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.08184 * group2.width, group2.minY + 0.44737 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.36559 * group2.width, group2.minY + 0.22368 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.28375 * group2.width, group2.minY + 0.44737 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.36559 * group2.width, group2.minY + 0.34722 * group2.height))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(group2.minX + 1.00000 * group2.width, group2.minY + 0.67105 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.73118 * group2.width, group2.minY + 0.34211 * group2.height), controlPoint1: CGPointMake(group2.minX + 1.00000 * group2.width, group2.minY + 0.48938 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.87965 * group2.width, group2.minY + 0.34211 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.46237 * group2.width, group2.minY + 0.67105 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.58272 * group2.width, group2.minY + 0.34211 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.46237 * group2.width, group2.minY + 0.48938 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.73118 * group2.width, group2.minY + 1.00000 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.46237 * group2.width, group2.minY + 0.85273 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.58272 * group2.width, group2.minY + 1.00000 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 1.00000 * group2.width, group2.minY + 0.67105 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.87965 * group2.width, group2.minY + 1.00000 * group2.height), controlPoint2: CGPointMake(group2.minX + 1.00000 * group2.width, group2.minY + 0.85273 * group2.height))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(group2.minX + 0.32258 * group2.width, group2.minY + 0.36842 * group2.height))
        bezier2Path.addLineToPoint(CGPointMake(group2.minX + 0.50538 * group2.width, group2.minY + 0.50000 * group2.height))
        iconColor.setStroke()
        bezier2Path.lineWidth = 10
        bezier2Path.stroke()
    }

    public class func drawBlock(#frame: CGRect, iconColor: UIColor) {


        //// Subframes
        let frame2 = CGRectMake(frame.minX + 48, frame.minY + 57, frame.width - 91, frame.height - 110)
        let group2: CGRect = CGRectMake(frame2.minX + 26.55, frame2.minY + 0.08, frame2.width - 52.55, frame2.height - 8.08)


        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 20, frame.minY + 20, frame.width - 39.5, frame.height - 39.5))
        iconColor.setStroke()
        oval2Path.lineWidth = 5
        oval2Path.stroke()


        //// Group 2
        //// Text Drawing
        var textPath = UIBezierPath()
        textPath.moveToPoint(CGPointMake(group2.minX + 0.68801 * group2.width, group2.minY + 0.36391 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.75610 * group2.width, group2.minY + 0.25660 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.73340 * group2.width, group2.minY + 0.33390 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.75610 * group2.width, group2.minY + 0.29813 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.69106 * group2.width, group2.minY + 0.15708 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.75610 * group2.width, group2.minY + 0.22049 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.73442 * group2.width, group2.minY + 0.18732 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.49289 * group2.width, group2.minY + 0.11171 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.64770 * group2.width, group2.minY + 0.12683 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.58164 * group2.width, group2.minY + 0.11171 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.30183 * group2.width, group2.minY + 0.15708 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.40481 * group2.width, group2.minY + 0.11171 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.34112 * group2.width, group2.minY + 0.12683 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.24289 * group2.width, group2.minY + 0.26337 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.26253 * group2.width, group2.minY + 0.18732 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.24289 * group2.width, group2.minY + 0.22275 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.31911 * group2.width, group2.minY + 0.37035 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.24289 * group2.width, group2.minY + 0.30896 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.26829 * group2.width, group2.minY + 0.34462 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.49898 * group2.width, group2.minY + 0.40894 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.36992 * group2.width, group2.minY + 0.39607 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.42988 * group2.width, group2.minY + 0.40894 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.68801 * group2.width, group2.minY + 0.36391 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.57961 * group2.width, group2.minY + 0.40894 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.64261 * group2.width, group2.minY + 0.39393 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPointMake(group2.minX + 0.72104 * group2.width, group2.minY + 0.84326 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.80488 * group2.width, group2.minY + 0.70684 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.77693 * group2.width, group2.minY + 0.81280 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.80488 * group2.width, group2.minY + 0.76732 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.71850 * group2.width, group2.minY + 0.56398 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.80488 * group2.width, group2.minY + 0.64410 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.77608 * group2.width, group2.minY + 0.59648 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.49695 * group2.width, group2.minY + 0.51523 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.66091 * group2.width, group2.minY + 0.53148 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.58706 * group2.width, group2.minY + 0.51523 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.28303 * group2.width, group2.minY + 0.56500 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.40955 * group2.width, group2.minY + 0.51523 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.33825 * group2.width, group2.minY + 0.53182 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.20020 * group2.width, group2.minY + 0.70278 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.22781 * group2.width, group2.minY + 0.59817 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.20020 * group2.width, group2.minY + 0.64410 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.27591 * group2.width, group2.minY + 0.83378 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.20020 * group2.width, group2.minY + 0.75333 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.22544 * group2.width, group2.minY + 0.79700 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.51016 * group2.width, group2.minY + 0.88896 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.32639 * group2.width, group2.minY + 0.87057 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.40447 * group2.width, group2.minY + 0.88896 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.72104 * group2.width, group2.minY + 0.84326 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.59485 * group2.width, group2.minY + 0.88896 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.66514 * group2.width, group2.minY + 0.87373 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPointMake(group2.minX + 0.13110 * group2.width, group2.minY + 0.40487 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.05081 * group2.width, group2.minY + 0.26405 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.07757 * group2.width, group2.minY + 0.36877 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.05081 * group2.width, group2.minY + 0.32182 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.16870 * group2.width, group2.minY + 0.07786 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.05081 * group2.width, group2.minY + 0.19183 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.09011 * group2.width, group2.minY + 0.12977 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.50305 * group2.width, group2.minY + 0.00000 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.24729 * group2.width, group2.minY + 0.02595 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.35874 * group2.width, group2.minY + 0.00000 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.83130 * group2.width, group2.minY + 0.07346 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.64262 * group2.width, group2.minY + 0.00000 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.75203 * group2.width, group2.minY + 0.02449 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.95020 * group2.width, group2.minY + 0.24509 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.91057 * group2.width, group2.minY + 0.12243 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.95020 * group2.width, group2.minY + 0.17964 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.88110 * group2.width, group2.minY + 0.39201 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.95020 * group2.width, group2.minY + 0.30557 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.92717 * group2.width, group2.minY + 0.35455 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.76118 * group2.width, group2.minY + 0.45430 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.85535 * group2.width, group2.minY + 0.41323 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.81538 * group2.width, group2.minY + 0.43399 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.90346 * group2.width, group2.minY + 0.51794 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.82148 * group2.width, group2.minY + 0.47281 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.86890 * group2.width, group2.minY + 0.49402 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 1.00000 * group2.width, group2.minY + 0.69397 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.96782 * group2.width, group2.minY + 0.56308 * group2.height), controlPoint2: CGPointMake(group2.minX + 1.00000 * group2.width, group2.minY + 0.62176 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.87093 * group2.width, group2.minY + 0.91097 * group2.height), controlPoint1: CGPointMake(group2.minX + 1.00000 * group2.width, group2.minY + 0.77928 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.95698 * group2.width, group2.minY + 0.85161 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.50610 * group2.width, group2.minY + 1.00000 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.78489 * group2.width, group2.minY + 0.97032 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.66328 * group2.width, group2.minY + 1.00000 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.14685 * group2.width, group2.minY + 0.92316 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.36450 * group2.width, group2.minY + 1.00000 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.24475 * group2.width, group2.minY + 0.97439 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.70007 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.04895 * group2.width, group2.minY + 0.87192 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.79756 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.06301 * group2.width, group2.minY + 0.55146 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.64274 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.02100 * group2.width, group2.minY + 0.59321 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.25000 * group2.width, group2.minY + 0.45565 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.10501 * group2.width, group2.minY + 0.50970 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.16734 * group2.width, group2.minY + 0.47777 * group2.height))
        textPath.addCurveToPoint(CGPointMake(group2.minX + 0.13110 * group2.width, group2.minY + 0.40487 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.19919 * group2.width, group2.minY + 0.44121 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.15955 * group2.width, group2.minY + 0.42428 * group2.height))
        textPath.closePath()
        iconColor.setFill()
        textPath.fill()
    }

    public class func drawKvo(#frame: CGRect, iconColor: UIColor) {


        //// Subframes
        let frame2 = CGRectMake(frame.minX + 48, frame.minY + 57, frame.width - 91, frame.height - 110)


        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 20, frame.minY + 20, frame.width - 39.5, frame.height - 39.5))
        iconColor.setStroke()
        oval2Path.lineWidth = 5
        oval2Path.stroke()


        //// Group 2


        //// Bezier 4 Drawing
        var bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(frame2.minX + 0.57285 * frame2.width, frame2.minY + 0.83794 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.52837 * frame2.width, frame2.minY + 0.83794 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.46165 * frame2.width, frame2.minY + 0.83794 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.46165 * frame2.width, frame2.minY + 0.76802 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.46165 * frame2.width, frame2.minY + 0.72141 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.46165 * frame2.width, frame2.minY + 0.55261 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.57555 * frame2.width, frame2.minY + 0.67197 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.62004 * frame2.width, frame2.minY + 0.71858 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.73394 * frame2.width, frame2.minY + 0.83794 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.57285 * frame2.width, frame2.minY + 0.83794 * frame2.height))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(frame2.minX + 0.57285 * frame2.width, frame2.minY + 0.69810 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.57285 * frame2.width, frame2.minY + 0.76802 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.52567 * frame2.width, frame2.minY + 0.81746 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.48119 * frame2.width, frame2.minY + 0.77085 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.52837 * frame2.width, frame2.minY + 0.72141 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.59510 * frame2.width, frame2.minY + 0.72141 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.59510 * frame2.width, frame2.minY + 0.76802 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.52837 * frame2.width, frame2.minY + 0.76802 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.52837 * frame2.width, frame2.minY + 0.69810 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.57285 * frame2.width, frame2.minY + 0.69810 * frame2.height))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(frame2.minX + 0.55061 * frame2.width, frame2.minY + 0.24363 * frame2.height))
        bezier4Path.addCurveToPoint(CGPointMake(frame2.minX + 0.47277 * frame2.width, frame2.minY + 0.16206 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.55061 * frame2.width, frame2.minY + 0.19858 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.51576 * frame2.width, frame2.minY + 0.16206 * frame2.height))
        bezier4Path.addCurveToPoint(CGPointMake(frame2.minX + 0.39492 * frame2.width, frame2.minY + 0.24363 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.42977 * frame2.width, frame2.minY + 0.16206 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.39492 * frame2.width, frame2.minY + 0.19858 * frame2.height))
        bezier4Path.addCurveToPoint(CGPointMake(frame2.minX + 0.47277 * frame2.width, frame2.minY + 0.32520 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.39492 * frame2.width, frame2.minY + 0.28868 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.42977 * frame2.width, frame2.minY + 0.32520 * frame2.height))
        bezier4Path.addCurveToPoint(CGPointMake(frame2.minX + 0.55061 * frame2.width, frame2.minY + 0.24363 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.51576 * frame2.width, frame2.minY + 0.32520 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.55061 * frame2.width, frame2.minY + 0.28868 * frame2.height))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(frame2.minX + 0.68406 * frame2.width, frame2.minY + 0.24363 * frame2.height))
        bezier4Path.addCurveToPoint(CGPointMake(frame2.minX + 0.47277 * frame2.width, frame2.minY + 0.46504 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.68406 * frame2.width, frame2.minY + 0.36591 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.58946 * frame2.width, frame2.minY + 0.46504 * frame2.height))
        bezier4Path.addCurveToPoint(CGPointMake(frame2.minX + 0.26147 * frame2.width, frame2.minY + 0.24363 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.35607 * frame2.width, frame2.minY + 0.46504 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.26147 * frame2.width, frame2.minY + 0.36591 * frame2.height))
        bezier4Path.addCurveToPoint(CGPointMake(frame2.minX + 0.47277 * frame2.width, frame2.minY + 0.02222 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.26147 * frame2.width, frame2.minY + 0.12135 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.35607 * frame2.width, frame2.minY + 0.02222 * frame2.height))
        bezier4Path.addCurveToPoint(CGPointMake(frame2.minX + 0.68406 * frame2.width, frame2.minY + 0.24363 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.58946 * frame2.width, frame2.minY + 0.02222 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.68406 * frame2.width, frame2.minY + 0.12135 * frame2.height))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(frame2.minX + 0.57285 * frame2.width, frame2.minY + 0.93117 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.52837 * frame2.width, frame2.minY + 0.93117 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.46165 * frame2.width, frame2.minY + 0.93117 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.46165 * frame2.width, frame2.minY + 0.86125 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.46165 * frame2.width, frame2.minY + 0.81463 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.46165 * frame2.width, frame2.minY + 0.64584 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.57555 * frame2.width, frame2.minY + 0.76519 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.62004 * frame2.width, frame2.minY + 0.81181 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.73394 * frame2.width, frame2.minY + 0.93117 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.57285 * frame2.width, frame2.minY + 0.93117 * frame2.height))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(frame2.minX + 0.57285 * frame2.width, frame2.minY + 0.79133 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.57285 * frame2.width, frame2.minY + 0.86125 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.52567 * frame2.width, frame2.minY + 0.91069 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.48119 * frame2.width, frame2.minY + 0.86407 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.52837 * frame2.width, frame2.minY + 0.81463 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.59510 * frame2.width, frame2.minY + 0.81463 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.59510 * frame2.width, frame2.minY + 0.86125 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.52837 * frame2.width, frame2.minY + 0.86125 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.52837 * frame2.width, frame2.minY + 0.79133 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.57285 * frame2.width, frame2.minY + 0.79133 * frame2.height))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(frame2.minX + 0.55061 * frame2.width, frame2.minY + 0.41843 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.55061 * frame2.width, frame2.minY + 0.97778 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.41716 * frame2.width, frame2.minY + 0.97778 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.41716 * frame2.width, frame2.minY + 0.41843 * frame2.height))
        bezier4Path.addLineToPoint(CGPointMake(frame2.minX + 0.55061 * frame2.width, frame2.minY + 0.41843 * frame2.height))
        bezier4Path.closePath()
        iconColor.setFill()
        bezier4Path.fill()
    }

    public class func drawNotification(#frame: CGRect, iconColor: UIColor) {


        //// Subframes
        let frame2 = CGRectMake(frame.minX + 43, frame.minY + 46, frame.width - 87, frame.height - 95)


        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 20, frame.minY + 20, frame.width - 39.5, frame.height - 39.5))
        iconColor.setStroke()
        oval2Path.lineWidth = 5
        oval2Path.stroke()


        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        UIColor.grayColor().setFill()
        bezierPath.fill()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(frame2.minX + 0.85195 * frame2.width, frame2.minY + 0.22825 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.85739 * frame2.width, frame2.minY + 0.27610 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.85841 * frame2.width, frame2.minY + 0.23817 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.86144 * frame2.width, frame2.minY + 0.24734 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.88916 * frame2.width, frame2.minY + 0.30311 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.87912 * frame2.width, frame2.minY + 0.28573 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.88461 * frame2.width, frame2.minY + 0.29285 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.74402 * frame2.width, frame2.minY + 0.88524 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.98021 * frame2.width, frame2.minY + 0.50856 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.91873 * frame2.width, frame2.minY + 0.75502 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.71471 * frame2.width, frame2.minY + 0.89327 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.73160 * frame2.width, frame2.minY + 0.89450 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.72798 * frame2.width, frame2.minY + 0.89460 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.70943 * frame2.width, frame2.minY + 0.89250 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.71294 * frame2.width, frame2.minY + 0.89309 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.71129 * frame2.width, frame2.minY + 0.89284 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.70128 * frame2.width, frame2.minY + 0.89078 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.70721 * frame2.width, frame2.minY + 0.89209 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.70454 * frame2.width, frame2.minY + 0.89152 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.67849 * frame2.width, frame2.minY + 0.91836 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.69348 * frame2.width, frame2.minY + 0.90879 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.68718 * frame2.width, frame2.minY + 0.91399 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.13198 * frame2.width, frame2.minY + 0.76376 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.48561 * frame2.width, frame2.minY + 1.01535 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.25423 * frame2.width, frame2.minY + 0.94986 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.12444 * frame2.width, frame2.minY + 0.73254 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.12328 * frame2.width, frame2.minY + 0.75053 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.12319 * frame2.width, frame2.minY + 0.74668 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.12478 * frame2.width, frame2.minY + 0.72950 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.12453 * frame2.width, frame2.minY + 0.73151 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.12464 * frame2.width, frame2.minY + 0.73052 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.09598 * frame2.width, frame2.minY + 0.70445 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.09201 * frame2.width, frame2.minY + 0.71782 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.10441 * frame2.width, frame2.minY + 0.72316 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.24128 * frame2.width, frame2.minY + 0.11834 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.00281 * frame2.width, frame2.minY + 0.49789 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.06459 * frame2.width, frame2.minY + 0.24891 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.27610 * frame2.width, frame2.minY + 0.11119 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.24932 * frame2.width, frame2.minY + 0.11240 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.25683 * frame2.width, frame2.minY + 0.10918 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.27833 * frame2.width, frame2.minY + 0.10369 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.27696 * frame2.width, frame2.minY + 0.10821 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.27769 * frame2.width, frame2.minY + 0.10572 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.30170 * frame2.width, frame2.minY + 0.07348 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.28916 * frame2.width, frame2.minY + 0.06926 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.28414 * frame2.width, frame2.minY + 0.08247 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.37606 * frame2.width, frame2.minY + 0.04390 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.32596 * frame2.width, frame2.minY + 0.06106 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.35085 * frame2.width, frame2.minY + 0.05123 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.48169 * frame2.width, frame2.minY + 0.02760 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.41091 * frame2.width, frame2.minY + 0.03376 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.44638 * frame2.width, frame2.minY + 0.02841 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.85195 * frame2.width, frame2.minY + 0.22825 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.62507 * frame2.width, frame2.minY + 0.02433 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.76590 * frame2.width, frame2.minY + 0.09614 * frame2.height))
        bezier3Path.closePath()
        bezier3Path.moveToPoint(CGPointMake(frame2.minX + 0.27439 * frame2.width, frame2.minY + 0.25207 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.26961 * frame2.width, frame2.minY + 0.25709 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.27278 * frame2.width, frame2.minY + 0.25372 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.27119 * frame2.width, frame2.minY + 0.25539 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.26961 * frame2.width, frame2.minY + 0.72404 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.14945 * frame2.width, frame2.minY + 0.38603 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.14945 * frame2.width, frame2.minY + 0.59510 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.70475 * frame2.width, frame2.minY + 0.72404 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.38977 * frame2.width, frame2.minY + 0.85299 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.58459 * frame2.width, frame2.minY + 0.85299 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.70475 * frame2.width, frame2.minY + 0.25709 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.82491 * frame2.width, frame2.minY + 0.59510 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.82491 * frame2.width, frame2.minY + 0.38603 * frame2.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame2.minX + 0.27439 * frame2.width, frame2.minY + 0.25207 * frame2.height), controlPoint1: CGPointMake(frame2.minX + 0.58617 * frame2.width, frame2.minY + 0.12984 * frame2.height), controlPoint2: CGPointMake(frame2.minX + 0.39488 * frame2.width, frame2.minY + 0.12816 * frame2.height))
        bezier3Path.closePath()
        iconColor.setFill()
        bezier3Path.fill()
    }

    public class func drawSegueIcon() {
        //// Color Declarations
        let color = UIColor(red: 0.817, green: 0.036, blue: 0.036, alpha: 1.000)

        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(2, 1.5, 30, 29.5))
        color.setStroke()
        oval2Path.lineWidth = 2
        oval2Path.stroke()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(4.44, 16.73))
        bezier3Path.addLineToPoint(CGPointMake(27, 16.73))
        bezier3Path.moveToPoint(CGPointMake(15.83, 4.98))
        bezier3Path.addLineToPoint(CGPointMake(27, 16.72))
        bezier3Path.addLineToPoint(CGPointMake(15.83, 28))
        color.setStroke()
        bezier3Path.lineWidth = 3
        bezier3Path.stroke()
    }

    public class func drawDelegateIcon() {
        //// Color Declarations
        let color = UIColor(red: 0.817, green: 0.036, blue: 0.036, alpha: 1.000)

        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(2, 1.5, 30, 29.5))
        color.setStroke()
        oval2Path.lineWidth = 2
        oval2Path.stroke()


        //// Group 2
        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(13.49, 12.69))
        bezier2Path.addCurveToPoint(CGPointMake(9.75, 9), controlPoint1: CGPointMake(13.49, 10.65), controlPoint2: CGPointMake(11.82, 9))
        bezier2Path.addCurveToPoint(CGPointMake(6, 12.69), controlPoint1: CGPointMake(7.68, 9), controlPoint2: CGPointMake(6, 10.65))
        bezier2Path.addCurveToPoint(CGPointMake(9.75, 16.38), controlPoint1: CGPointMake(6, 14.73), controlPoint2: CGPointMake(7.68, 16.38))
        bezier2Path.addCurveToPoint(CGPointMake(13.49, 12.69), controlPoint1: CGPointMake(11.82, 16.38), controlPoint2: CGPointMake(13.49, 14.73))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(26.5, 20.07))
        bezier2Path.addCurveToPoint(CGPointMake(20.99, 14.64), controlPoint1: CGPointMake(26.5, 17.07), controlPoint2: CGPointMake(24.03, 14.64))
        bezier2Path.addCurveToPoint(CGPointMake(15.48, 20.07), controlPoint1: CGPointMake(17.95, 14.64), controlPoint2: CGPointMake(15.48, 17.07))
        bezier2Path.addCurveToPoint(CGPointMake(20.99, 25.5), controlPoint1: CGPointMake(15.48, 23.07), controlPoint2: CGPointMake(17.95, 25.5))
        bezier2Path.addCurveToPoint(CGPointMake(26.5, 20.07), controlPoint1: CGPointMake(24.03, 25.5), controlPoint2: CGPointMake(26.5, 23.07))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(12.61, 15.08))
        bezier2Path.addLineToPoint(CGPointMake(16.36, 17.25))
        color.setStroke()
        bezier2Path.lineWidth = 3
        bezier2Path.stroke()
    }

    public class func drawBlockIcon() {
        //// Color Declarations
        let color = UIColor(red: 0.817, green: 0.036, blue: 0.036, alpha: 1.000)

        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(2, 1.5, 30, 29.5))
        color.setStroke()
        oval2Path.lineWidth = 2
        oval2Path.stroke()


        //// Group 2
        //// Text Drawing
        var textPath = UIBezierPath()
        textPath.moveToPoint(CGPointMake(19.87, 13.42))
        textPath.addCurveToPoint(CGPointMake(20.99, 10.96), controlPoint1: CGPointMake(20.61, 12.73), controlPoint2: CGPointMake(20.99, 11.91))
        textPath.addCurveToPoint(CGPointMake(19.92, 8.68), controlPoint1: CGPointMake(20.99, 10.13), controlPoint2: CGPointMake(20.63, 9.37))
        textPath.addCurveToPoint(CGPointMake(16.66, 7.64), controlPoint1: CGPointMake(19.2, 7.99), controlPoint2: CGPointMake(18.12, 7.64))
        textPath.addCurveToPoint(CGPointMake(13.51, 8.68), controlPoint1: CGPointMake(15.21, 7.64), controlPoint2: CGPointMake(14.16, 7.99))
        textPath.addCurveToPoint(CGPointMake(12.54, 11.12), controlPoint1: CGPointMake(12.87, 9.37), controlPoint2: CGPointMake(12.54, 10.19))
        textPath.addCurveToPoint(CGPointMake(13.8, 13.57), controlPoint1: CGPointMake(12.54, 12.16), controlPoint2: CGPointMake(12.96, 12.98))
        textPath.addCurveToPoint(CGPointMake(16.76, 14.45), controlPoint1: CGPointMake(14.63, 14.16), controlPoint2: CGPointMake(15.62, 14.45))
        textPath.addCurveToPoint(CGPointMake(19.87, 13.42), controlPoint1: CGPointMake(18.08, 14.45), controlPoint2: CGPointMake(19.12, 14.11))
        textPath.closePath()
        textPath.moveToPoint(CGPointMake(20.41, 24.41))
        textPath.addCurveToPoint(CGPointMake(21.79, 21.28), controlPoint1: CGPointMake(21.33, 23.71), controlPoint2: CGPointMake(21.79, 22.67))
        textPath.addCurveToPoint(CGPointMake(20.37, 18.01), controlPoint1: CGPointMake(21.79, 19.84), controlPoint2: CGPointMake(21.32, 18.75))
        textPath.addCurveToPoint(CGPointMake(16.72, 16.89), controlPoint1: CGPointMake(19.42, 17.26), controlPoint2: CGPointMake(18.21, 16.89))
        textPath.addCurveToPoint(CGPointMake(13.2, 18.03), controlPoint1: CGPointMake(15.29, 16.89), controlPoint2: CGPointMake(14.11, 17.27))
        textPath.addCurveToPoint(CGPointMake(11.84, 21.19), controlPoint1: CGPointMake(12.3, 18.79), controlPoint2: CGPointMake(11.84, 19.84))
        textPath.addCurveToPoint(CGPointMake(13.09, 24.19), controlPoint1: CGPointMake(11.84, 22.35), controlPoint2: CGPointMake(12.26, 23.35))
        textPath.addCurveToPoint(CGPointMake(16.94, 25.46), controlPoint1: CGPointMake(13.92, 25.03), controlPoint2: CGPointMake(15.2, 25.46))
        textPath.addCurveToPoint(CGPointMake(20.41, 24.41), controlPoint1: CGPointMake(18.33, 25.46), controlPoint2: CGPointMake(19.49, 25.11))
        textPath.closePath()
        textPath.moveToPoint(CGPointMake(10.7, 14.36))
        textPath.addCurveToPoint(CGPointMake(9.38, 11.13), controlPoint1: CGPointMake(9.82, 13.53), controlPoint2: CGPointMake(9.38, 12.46))
        textPath.addCurveToPoint(CGPointMake(11.32, 6.86), controlPoint1: CGPointMake(9.38, 9.48), controlPoint2: CGPointMake(10.03, 8.05))
        textPath.addCurveToPoint(CGPointMake(16.82, 5.08), controlPoint1: CGPointMake(12.62, 5.67), controlPoint2: CGPointMake(14.45, 5.08))
        textPath.addCurveToPoint(CGPointMake(22.22, 6.76), controlPoint1: CGPointMake(19.12, 5.08), controlPoint2: CGPointMake(20.92, 5.64))
        textPath.addCurveToPoint(CGPointMake(24.18, 10.7), controlPoint1: CGPointMake(23.53, 7.89), controlPoint2: CGPointMake(24.18, 9.2))
        textPath.addCurveToPoint(CGPointMake(23.04, 14.06), controlPoint1: CGPointMake(24.18, 12.08), controlPoint2: CGPointMake(23.8, 13.21))
        textPath.addCurveToPoint(CGPointMake(21.07, 15.49), controlPoint1: CGPointMake(22.62, 14.55), controlPoint2: CGPointMake(21.96, 15.03))
        textPath.addCurveToPoint(CGPointMake(23.41, 16.95), controlPoint1: CGPointMake(22.06, 15.92), controlPoint2: CGPointMake(22.84, 16.4))
        textPath.addCurveToPoint(CGPointMake(25, 20.99), controlPoint1: CGPointMake(24.47, 17.99), controlPoint2: CGPointMake(25, 19.33))
        textPath.addCurveToPoint(CGPointMake(22.88, 25.96), controlPoint1: CGPointMake(25, 22.94), controlPoint2: CGPointMake(24.29, 24.6))
        textPath.addCurveToPoint(CGPointMake(16.87, 28), controlPoint1: CGPointMake(21.46, 27.32), controlPoint2: CGPointMake(19.46, 28))
        textPath.addCurveToPoint(CGPointMake(10.96, 26.24), controlPoint1: CGPointMake(14.54, 28), controlPoint2: CGPointMake(12.57, 27.41))
        textPath.addCurveToPoint(CGPointMake(8.55, 21.13), controlPoint1: CGPointMake(9.35, 25.06), controlPoint2: CGPointMake(8.55, 23.36))
        textPath.addCurveToPoint(CGPointMake(9.58, 17.72), controlPoint1: CGPointMake(8.55, 19.81), controlPoint2: CGPointMake(8.89, 18.68))
        textPath.addCurveToPoint(CGPointMake(12.66, 15.52), controlPoint1: CGPointMake(10.28, 16.76), controlPoint2: CGPointMake(11.3, 16.03))
        textPath.addCurveToPoint(CGPointMake(10.7, 14.36), controlPoint1: CGPointMake(11.82, 15.19), controlPoint2: CGPointMake(11.17, 14.8))
        textPath.closePath()
        color.setFill()
        textPath.fill()
    }

    public class func drawKvoIcon() {
        //// Color Declarations
        let color = UIColor(red: 0.817, green: 0.036, blue: 0.036, alpha: 1.000)

        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(2, 1.5, 30, 29.5))
        color.setStroke()
        oval2Path.lineWidth = 2
        oval2Path.stroke()


        //// Bezier 4 Drawing
        var bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(19.74, 23.93))
        bezier4Path.addLineToPoint(CGPointMake(18.56, 23.93))
        bezier4Path.addLineToPoint(CGPointMake(16.8, 23.93))
        bezier4Path.addLineToPoint(CGPointMake(16.8, 22.39))
        bezier4Path.addLineToPoint(CGPointMake(16.8, 21.37))
        bezier4Path.addLineToPoint(CGPointMake(16.8, 17.66))
        bezier4Path.addLineToPoint(CGPointMake(19.81, 20.28))
        bezier4Path.addLineToPoint(CGPointMake(20.99, 21.3))
        bezier4Path.addLineToPoint(CGPointMake(24, 23.93))
        bezier4Path.addLineToPoint(CGPointMake(19.74, 23.93))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(19.74, 20.85))
        bezier4Path.addLineToPoint(CGPointMake(19.74, 22.39))
        bezier4Path.addLineToPoint(CGPointMake(18.49, 23.48))
        bezier4Path.addLineToPoint(CGPointMake(17.31, 22.45))
        bezier4Path.addLineToPoint(CGPointMake(18.56, 21.37))
        bezier4Path.addLineToPoint(CGPointMake(20.33, 21.37))
        bezier4Path.addLineToPoint(CGPointMake(20.33, 22.39))
        bezier4Path.addLineToPoint(CGPointMake(18.56, 22.39))
        bezier4Path.addLineToPoint(CGPointMake(18.56, 20.85))
        bezier4Path.addLineToPoint(CGPointMake(19.74, 20.85))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(19.15, 10.87))
        bezier4Path.addCurveToPoint(CGPointMake(17.09, 9.07), controlPoint1: CGPointMake(19.15, 9.88), controlPoint2: CGPointMake(18.23, 9.07))
        bezier4Path.addCurveToPoint(CGPointMake(15.03, 10.87), controlPoint1: CGPointMake(15.95, 9.07), controlPoint2: CGPointMake(15.03, 9.88))
        bezier4Path.addCurveToPoint(CGPointMake(17.09, 12.66), controlPoint1: CGPointMake(15.03, 11.86), controlPoint2: CGPointMake(15.95, 12.66))
        bezier4Path.addCurveToPoint(CGPointMake(19.15, 10.87), controlPoint1: CGPointMake(18.23, 12.66), controlPoint2: CGPointMake(19.15, 11.86))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(22.68, 10.87))
        bezier4Path.addCurveToPoint(CGPointMake(17.09, 15.73), controlPoint1: CGPointMake(22.68, 13.55), controlPoint2: CGPointMake(20.18, 15.73))
        bezier4Path.addCurveToPoint(CGPointMake(11.5, 10.87), controlPoint1: CGPointMake(14, 15.73), controlPoint2: CGPointMake(11.5, 13.55))
        bezier4Path.addCurveToPoint(CGPointMake(17.09, 6), controlPoint1: CGPointMake(11.5, 8.18), controlPoint2: CGPointMake(14, 6))
        bezier4Path.addCurveToPoint(CGPointMake(22.68, 10.87), controlPoint1: CGPointMake(20.18, 6), controlPoint2: CGPointMake(22.68, 8.18))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(19.74, 25.98))
        bezier4Path.addLineToPoint(CGPointMake(18.56, 25.98))
        bezier4Path.addLineToPoint(CGPointMake(16.8, 25.98))
        bezier4Path.addLineToPoint(CGPointMake(16.8, 24.44))
        bezier4Path.addLineToPoint(CGPointMake(16.8, 23.41))
        bezier4Path.addLineToPoint(CGPointMake(16.8, 19.7))
        bezier4Path.addLineToPoint(CGPointMake(19.81, 22.33))
        bezier4Path.addLineToPoint(CGPointMake(20.99, 23.35))
        bezier4Path.addLineToPoint(CGPointMake(24, 25.98))
        bezier4Path.addLineToPoint(CGPointMake(19.74, 25.98))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(19.74, 22.9))
        bezier4Path.addLineToPoint(CGPointMake(19.74, 24.44))
        bezier4Path.addLineToPoint(CGPointMake(18.49, 25.53))
        bezier4Path.addLineToPoint(CGPointMake(17.31, 24.5))
        bezier4Path.addLineToPoint(CGPointMake(18.56, 23.41))
        bezier4Path.addLineToPoint(CGPointMake(20.33, 23.41))
        bezier4Path.addLineToPoint(CGPointMake(20.33, 24.44))
        bezier4Path.addLineToPoint(CGPointMake(18.56, 24.44))
        bezier4Path.addLineToPoint(CGPointMake(18.56, 22.9))
        bezier4Path.addLineToPoint(CGPointMake(19.74, 22.9))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(19.15, 14.71))
        bezier4Path.addLineToPoint(CGPointMake(19.15, 27))
        bezier4Path.addLineToPoint(CGPointMake(15.62, 27))
        bezier4Path.addLineToPoint(CGPointMake(15.62, 14.71))
        bezier4Path.addLineToPoint(CGPointMake(19.15, 14.71))
        bezier4Path.closePath()
        color.setFill()
        bezier4Path.fill()
    }

    public class func drawNotificationIcon() {
        //// Color Declarations
        let color = UIColor(red: 0.817, green: 0.036, blue: 0.036, alpha: 1.000)

        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(2, 1.5, 30, 29.5))
        color.setStroke()
        oval2Path.lineWidth = 2
        oval2Path.stroke()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(26.21, 10.53))
        bezier3Path.addCurveToPoint(CGPointMake(26.34, 11.61), controlPoint1: CGPointMake(26.37, 10.75), controlPoint2: CGPointMake(26.45, 10.96))
        bezier3Path.addCurveToPoint(CGPointMake(27.15, 12.22), controlPoint1: CGPointMake(26.89, 11.83), controlPoint2: CGPointMake(27.03, 11.99))
        bezier3Path.addCurveToPoint(CGPointMake(23.48, 25.36), controlPoint1: CGPointMake(29.45, 16.86), controlPoint2: CGPointMake(27.9, 22.42))
        bezier3Path.addCurveToPoint(CGPointMake(22.74, 25.54), controlPoint1: CGPointMake(23.16, 25.57), controlPoint2: CGPointMake(23.07, 25.57))
        bezier3Path.addCurveToPoint(CGPointMake(22.6, 25.52), controlPoint1: CGPointMake(22.69, 25.53), controlPoint2: CGPointMake(22.65, 25.53))
        bezier3Path.addCurveToPoint(CGPointMake(22.4, 25.48), controlPoint1: CGPointMake(22.55, 25.51), controlPoint2: CGPointMake(22.48, 25.5))
        bezier3Path.addCurveToPoint(CGPointMake(21.82, 26.1), controlPoint1: CGPointMake(22.2, 25.89), controlPoint2: CGPointMake(22.04, 26.01))
        bezier3Path.addCurveToPoint(CGPointMake(8, 22.62), controlPoint1: CGPointMake(16.94, 28.29), controlPoint2: CGPointMake(11.09, 26.82))
        bezier3Path.addCurveToPoint(CGPointMake(7.81, 21.91), controlPoint1: CGPointMake(7.78, 22.32), controlPoint2: CGPointMake(7.78, 22.23))
        bezier3Path.addCurveToPoint(CGPointMake(7.82, 21.84), controlPoint1: CGPointMake(7.81, 21.89), controlPoint2: CGPointMake(7.82, 21.87))
        bezier3Path.addCurveToPoint(CGPointMake(7.09, 21.28), controlPoint1: CGPointMake(6.99, 21.58), controlPoint2: CGPointMake(7.3, 21.7))
        bezier3Path.addCurveToPoint(CGPointMake(10.77, 8.05), controlPoint1: CGPointMake(4.74, 16.62), controlPoint2: CGPointMake(6.3, 11))
        bezier3Path.addCurveToPoint(CGPointMake(11.65, 7.89), controlPoint1: CGPointMake(10.97, 7.92), controlPoint2: CGPointMake(11.16, 7.84))
        bezier3Path.addCurveToPoint(CGPointMake(11.7, 7.72), controlPoint1: CGPointMake(11.67, 7.82), controlPoint2: CGPointMake(11.69, 7.77))
        bezier3Path.addCurveToPoint(CGPointMake(12.29, 7.04), controlPoint1: CGPointMake(11.98, 6.94), controlPoint2: CGPointMake(11.85, 7.24))
        bezier3Path.addCurveToPoint(CGPointMake(14.17, 6.37), controlPoint1: CGPointMake(12.91, 6.76), controlPoint2: CGPointMake(13.54, 6.54))
        bezier3Path.addCurveToPoint(CGPointMake(16.84, 6), controlPoint1: CGPointMake(15.05, 6.14), controlPoint2: CGPointMake(15.95, 6.02))
        bezier3Path.addCurveToPoint(CGPointMake(26.21, 10.53), controlPoint1: CGPointMake(20.47, 5.93), controlPoint2: CGPointMake(24.03, 7.55))
        bezier3Path.closePath()
        bezier3Path.moveToPoint(CGPointMake(11.6, 11.07))
        bezier3Path.addCurveToPoint(CGPointMake(11.48, 11.18), controlPoint1: CGPointMake(11.56, 11.11), controlPoint2: CGPointMake(11.52, 11.14))
        bezier3Path.addCurveToPoint(CGPointMake(11.48, 21.72), controlPoint1: CGPointMake(8.44, 14.09), controlPoint2: CGPointMake(8.44, 18.81))
        bezier3Path.addCurveToPoint(CGPointMake(22.49, 21.72), controlPoint1: CGPointMake(14.52, 24.63), controlPoint2: CGPointMake(19.45, 24.63))
        bezier3Path.addCurveToPoint(CGPointMake(22.49, 11.18), controlPoint1: CGPointMake(25.52, 18.81), controlPoint2: CGPointMake(25.52, 14.09))
        bezier3Path.addCurveToPoint(CGPointMake(11.6, 11.07), controlPoint1: CGPointMake(19.49, 8.31), controlPoint2: CGPointMake(14.65, 8.27))
        bezier3Path.closePath()
        color.setFill()
        bezier3Path.fill()
    }

    public class func drawCredit() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let color = UIColor(red: 0.817, green: 0.036, blue: 0.036, alpha: 1.000)

        //// Star Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 17, 17)
        CGContextScaleCTM(context, 0.5, 0.4)

        var starPath = UIBezierPath()
        starPath.moveToPoint(CGPointMake(0, -25))
        starPath.addLineToPoint(CGPointMake(6.4, -8.81))
        starPath.addLineToPoint(CGPointMake(23.78, -7.73))
        starPath.addLineToPoint(CGPointMake(10.35, 3.36))
        starPath.addLineToPoint(CGPointMake(14.69, 20.23))
        starPath.addLineToPoint(CGPointMake(0, 10.89))
        starPath.addLineToPoint(CGPointMake(-14.69, 20.23))
        starPath.addLineToPoint(CGPointMake(-10.35, 3.36))
        starPath.addLineToPoint(CGPointMake(-23.78, -7.73))
        starPath.addLineToPoint(CGPointMake(-6.4, -8.81))
        starPath.closePath()
        color.setStroke()
        starPath.lineWidth = 5
        starPath.stroke()

        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSegue(#frame: CGRect, iconColor: UIColor) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            StyleKit.drawSegue(frame: frame, iconColor: iconColor)

        let imageOfSegue = UIGraphicsGetImageFromCurrentImageContext()!.imageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate)
        UIGraphicsEndImageContext()

        return imageOfSegue
    }

    public class func imageOfDelegat(#frame: CGRect, iconColor: UIColor) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            StyleKit.drawDelegat(frame: frame, iconColor: iconColor)

        let imageOfDelegat = UIGraphicsGetImageFromCurrentImageContext()!.imageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate)
        UIGraphicsEndImageContext()

        return imageOfDelegat
    }

    public class func imageOfBlock(#frame: CGRect, iconColor: UIColor) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            StyleKit.drawBlock(frame: frame, iconColor: iconColor)

        let imageOfBlock = UIGraphicsGetImageFromCurrentImageContext()!.imageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate)
        UIGraphicsEndImageContext()

        return imageOfBlock
    }

    public class func imageOfKvo(#frame: CGRect, iconColor: UIColor) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            StyleKit.drawKvo(frame: frame, iconColor: iconColor)

        let imageOfKvo = UIGraphicsGetImageFromCurrentImageContext()!.imageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate)
        UIGraphicsEndImageContext()

        return imageOfKvo
    }

    public class func imageOfNotification(#frame: CGRect, iconColor: UIColor) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            StyleKit.drawNotification(frame: frame, iconColor: iconColor)

        let imageOfNotification = UIGraphicsGetImageFromCurrentImageContext()!.imageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate)
        UIGraphicsEndImageContext()

        return imageOfNotification
    }

    public class var imageOfSegueIcon: UIImage {
        if Cache.imageOfSegueIcon != nil {
            return Cache.imageOfSegueIcon!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(34, 34), false, 0)
            StyleKit.drawSegueIcon()

        Cache.imageOfSegueIcon = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfSegueIcon!
    }

    public class var imageOfDelegateIcon: UIImage {
        if Cache.imageOfDelegateIcon != nil {
            return Cache.imageOfDelegateIcon!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(34, 34), false, 0)
            StyleKit.drawDelegateIcon()

        Cache.imageOfDelegateIcon = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfDelegateIcon!
    }

    public class var imageOfBlockIcon: UIImage {
        if Cache.imageOfBlockIcon != nil {
            return Cache.imageOfBlockIcon!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(34, 34), false, 0)
            StyleKit.drawBlockIcon()

        Cache.imageOfBlockIcon = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfBlockIcon!
    }

    public class var imageOfKvoIcon: UIImage {
        if Cache.imageOfKvoIcon != nil {
            return Cache.imageOfKvoIcon!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(34, 34), false, 0)
            StyleKit.drawKvoIcon()

        Cache.imageOfKvoIcon = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfKvoIcon!
    }

    public class var imageOfNotificationIcon: UIImage {
        if Cache.imageOfNotificationIcon != nil {
            return Cache.imageOfNotificationIcon!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(34, 34), false, 0)
            StyleKit.drawNotificationIcon()

        Cache.imageOfNotificationIcon = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfNotificationIcon!
    }

    public class var imageOfCredit: UIImage {
        if Cache.imageOfCredit != nil {
            return Cache.imageOfCredit!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(34, 34), false, 0)
            StyleKit.drawCredit()

        Cache.imageOfCredit = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfCredit!
    }

    //// Customization Infrastructure

    @IBOutlet var segueIconTargets: [AnyObject]! {
        get { return Cache.segueIconTargets }
        set {
            Cache.segueIconTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(StyleKit.imageOfSegueIcon)
            }
        }
    }

    @IBOutlet var delegateIconTargets: [AnyObject]! {
        get { return Cache.delegateIconTargets }
        set {
            Cache.delegateIconTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(StyleKit.imageOfDelegateIcon)
            }
        }
    }

    @IBOutlet var blockIconTargets: [AnyObject]! {
        get { return Cache.blockIconTargets }
        set {
            Cache.blockIconTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(StyleKit.imageOfBlockIcon)
            }
        }
    }

    @IBOutlet var kvoIconTargets: [AnyObject]! {
        get { return Cache.kvoIconTargets }
        set {
            Cache.kvoIconTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(StyleKit.imageOfKvoIcon)
            }
        }
    }

    @IBOutlet var notificationIconTargets: [AnyObject]! {
        get { return Cache.notificationIconTargets }
        set {
            Cache.notificationIconTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(StyleKit.imageOfNotificationIcon)
            }
        }
    }

    @IBOutlet var creditTargets: [AnyObject]! {
        get { return Cache.creditTargets }
        set {
            Cache.creditTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(StyleKit.imageOfCredit)
            }
        }
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
